### ISSUE TITLE
Mipmap sampling for textures

### ISSUE THREAD

**Issue by jsulpis** [CodyJasonBennett/four#10]
Hello,

I am getting some artifacts when using `Texture` uniforms, which I think are due to the lack of mipmaps for the textures. I see that the `Filter` option only accepts `nearest` and `linear`, but no mipmaps.

Do you have any plan on implementing mipmaps ? Or do you have a workaround ? I could load the textures on the GPU using directly the native WebGL API, but then since I don't have access to the program, I don't know how to bind them to the uniforms.

Thank you !

**Comment by CodyJasonBennett** [comment]
I've refrained from adding mipmaps since it introduces an asymmetrical API between WebGL and WebGPU since the latter does not implement it natively (instead, you're expected to implement it yourself).

WebGPU gives better tools for this though, and although I first implemented this library to show how similar you can design WebGL2/WebGPU, I can allow such a common case for WebGL.

For future reference, if you find yourself wanting low-level access to renderer state, refer to mangled internals as follows:

https://github.com/CodyJasonBennett/four/blob/7c50eae176c2f0077e49923b59876934a5d84620/vite.config.ts#L4-L14

**Comment by CodyJasonBennett** [comment]
Released in [v0.3.0](https://github.com/CodyJasonBennett/four/releases/tag/v0.3.0) under `Sampler.generateMipmaps`.
